### ISSUE TITLE
There is a user that is always online 

### ISSUE THREAD

**Issue by azzi907** [cometchat-pro/react-native-chat-app#26] opened 2021-05-03 05:07 UTC
### Describe the problem

> There is a user that is always online due to some issue on the back-end

### What was the expected behavior?

> the mentioned user should not be online when the user is not using the app just like all other users.

### Reproduction

> App id: 27437a7055e4f88
   User UID: 5fce4a99a6cb320029adadb5

- the user UID and AppId is mentioned. the mentioned user is always online leading testers to believe there is something  wrong with the backend of CometChat.

**Comment by azzi907** [comment] 2021-05-05 06:41
@paarthsabharwal any update on this 
@JitvarP anyone?

**Comment by TirathBhuva** [comment] 2021-05-26 05:05
Hey @azzi907,
We checked it out but we were unable to reproduce this issue, also we found that there are two users with the same name so I guess it was causing the issue. Can you check again and let us know if you are still facing this issue.

**Comment by proveshapyne** [comment] 2021-06-16 16:08
Hi @azzi907,

I am closing this ticket as we have reached out to you via email. We can stay connected on the email thread we have going. 
Thank you.

Regards,
Provesha

**Closed** 2021-07-16 10:03 UTC
